import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const packageJson = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'))
const builder = await readFile(new URL('../electron-builder.yml', import.meta.url), 'utf8')
const html = await readFile(new URL('../src/renderer/index.html', import.meta.url), 'utf8')
const main = await readFile(new URL('../src/main/index.ts', import.meta.url), 'utf8')
const appRenderer = await readFile(new URL('../src/renderer/src/App.tsx', import.meta.url), 'utf8')
const rendererMain = await readFile(new URL('../src/renderer/src/main.tsx', import.meta.url), 'utf8')
const startupTheme = await readFile(new URL('../src/renderer/src/startupTheme.ts', import.meta.url), 'utf8')
const normalizeAddress = await readFile(new URL('../src/renderer/src/normalizeAddress.ts', import.meta.url), 'utf8')
const styles = await readFile(new URL('../src/renderer/src/styles.css', import.meta.url), 'utf8')
const userAgent = await readFile(new URL('../src/main/browser/userAgent.ts', import.meta.url), 'utf8')
const imageTheme = await readFile(new URL('../src/main/browser/imageTheme.ts', import.meta.url), 'utf8')
const browserView = await readFile(new URL('../src/main/browser/view.ts', import.meta.url), 'utf8')
const screenshotCapture = await readFile(new URL('../src/main/screenshots/captureScreenshot.ts', import.meta.url), 'utf8')
const browserIpc = await readFile(new URL('../src/main/ipc/browser.ts', import.meta.url), 'utf8')
const preload = await readFile(new URL('../src/preload/index.ts', import.meta.url), 'utf8')
const browserContracts = await readFile(new URL('../src/shared/contracts/browser.ts', import.meta.url), 'utf8')
const settingsPanel = await readFile(new URL('../src/renderer/src/components/SettingsPanel.tsx', import.meta.url), 'utf8')
const deviceToolbar = await readFile(new URL('../src/renderer/src/components/DeviceToolbar.tsx', import.meta.url), 'utf8')
const devPanel = await readFile(new URL('../src/renderer/src/components/DevPanel.tsx', import.meta.url), 'utf8')
const errorCenter = await readFile(new URL('../src/renderer/src/features/errors/ErrorCenter.tsx', import.meta.url), 'utf8')
const elementsInspector = await readFile(new URL('../src/renderer/src/features/elements/ElementsInspector.tsx', import.meta.url), 'utf8')
const apiClient = await readFile(new URL('../src/renderer/src/features/api/ApiClient.tsx', import.meta.url), 'utf8')
const storageInspector = await readFile(new URL('../src/renderer/src/features/storage/StorageInspector.tsx', import.meta.url), 'utf8')
const historyPanel = await readFile(new URL('../src/renderer/src/components/HistoryPanel.tsx', import.meta.url), 'utf8')
const tabBar = await readFile(new URL('../src/renderer/src/components/TabBar.tsx', import.meta.url), 'utf8')
const devicesCanvasStore = await readFile(new URL('../src/renderer/src/stores/devicesCanvas.ts', import.meta.url), 'utf8')
const tabsStore = await readFile(new URL('../src/renderer/src/stores/tabs.ts', import.meta.url), 'utf8')
const devicePresets = await readFile(new URL('../src/renderer/src/devices/presets.ts', import.meta.url), 'utf8')
const tooltipLayer = await readFile(new URL('../src/renderer/src/components/TooltipLayer.tsx', import.meta.url), 'utf8')
const gitService = await readFile(new URL('../src/main/git/git.service.ts', import.meta.url), 'utf8')
const gitContextService = await readFile(new URL('../src/main/git/git-context.service.ts', import.meta.url), 'utf8')
const sourceCodeReader = await readFile(new URL('../src/main/git/source-code-reader.service.ts', import.meta.url), 'utf8')
const gitContracts = await readFile(new URL('../src/shared/contracts/git.ts', import.meta.url), 'utf8')
const githubContracts = await readFile(new URL('../src/shared/contracts/github.ts', import.meta.url), 'utf8')
const githubProvider = await readFile(new URL('../src/main/github/github.provider.ts', import.meta.url), 'utf8')
const githubContextService = await readFile(new URL('../src/main/github/github-context.service.ts', import.meta.url), 'utf8')
const database = await readFile(new URL('../src/main/storage/database.ts', import.meta.url), 'utf8')
const settingsRepository = await readFile(new URL('../src/main/storage/SettingsRepository.ts', import.meta.url), 'utf8')
const startupConfigRepository = await readFile(new URL('../src/main/storage/StartupConfigRepository.ts', import.meta.url), 'utf8')
const workspaceRepository = await readFile(new URL('../src/main/storage/WorkspaceRepository.ts', import.meta.url), 'utf8')
const pageStorage = await readFile(new URL('../src/main/storage/PageStorage.ts', import.meta.url), 'utf8')
const tabManager = await readFile(new URL('../src/main/tabs/TabManager.ts', import.meta.url), 'utf8')
const deviceViewManager = await readFile(new URL('../src/main/devices/DeviceViewManager.ts', import.meta.url), 'utf8')
const workspaceManager = await readFile(new URL('../src/main/workspaces/WorkspaceManager.ts', import.meta.url), 'utf8')
const networkCollector = await readFile(new URL('../src/main/devtools/NetworkCollector.ts', import.meta.url), 'utf8')
const consoleCollector = await readFile(new URL('../src/main/devtools/ConsoleCollector.ts', import.meta.url), 'utf8')
const pageElements = await readFile(new URL('../src/main/devtools/PageElements.ts', import.meta.url), 'utf8')
const shortcuts = await readFile(new URL('../src/shared/shortcuts.ts', import.meta.url), 'utf8')
const commandShortcuts = await readFile(new URL('../src/main/browser/commandShortcuts.ts', import.meta.url), 'utf8')
const commandRegistry = await readFile(new URL('../src/renderer/src/commands/registry.ts', import.meta.url), 'utf8')
const commandPalette = await readFile(new URL('../src/renderer/src/components/CommandPalette.tsx', import.meta.url), 'utf8')
const consoleInspector = await readFile(new URL('../src/renderer/src/features/console/ConsoleInspector.tsx', import.meta.url), 'utf8')

test('distribution scripts and targets are configured', () => {
  for (const script of ['dev', 'build', 'typecheck', 'test', 'package']) assert.equal(typeof packageJson.scripts[script], 'string')
  assert.equal(packageJson.desktopName, 'Stackly')
  assert.match(packageJson.author.email, /@/)
  for (const target of ['AppImage', 'nsis', 'dmg']) assert.match(builder, new RegExp(target))
  assert.match(packageJson.scripts['package:deb'], /--linux deb/)
})

test('prebuilt native modules are unpacked from ASAR', () => {
  assert.match(builder, /asar: true/)
  assert.match(builder, /node_modules\/node-pty/)
  assert.doesNotMatch(builder, /node_modules\/better-sqlite3/)
  assert.match(builder, /npmRebuild: false/)
  assert.match(builder, /!\*\*\/\*\.map/)
  assert.equal(packageJson.scripts.postinstall, 'node scripts/verify-native-prebuilds.mjs')
})

test('default Electron builds are downloaded from the official npm release', () => {
  assert.equal(packageJson.devDependencies.electron, '44.1.0')
  assert.match(builder, /electronVersion: 44\.1\.0/)
  assert.doesNotMatch(builder, /electronDownload:/)
  assert.doesNotMatch(builder, /castlabs|wvcus/)
})

test('production shell is local and has a restrictive CSP', () => {
  assert.match(main, /!app\.isPackaged && process\.env\.ELECTRON_RENDERER_URL/)
  assert.doesNotMatch(html, /unsafe-eval/)
  assert.doesNotMatch(html, /ws:\/\/(localhost|127\.0\.0\.1)/)
  assert.match(html, /script-src 'self'/)
  assert.match(html, /img-src 'self' data: blob: https: file:/)
})

test('package configuration contains no development machine path', () => {
  assert.doesNotMatch(JSON.stringify(packageJson) + builder + main, /\/home\/|[A-Z]:\\Users\\/)
})

test('address bar treats plain text like a browser search', () => {
  assert.match(normalizeAddress, /www\.google\.com\/search\?q=/)
  assert.match(normalizeAddress, /encodeURIComponent\(value\)/)
  assert.match(normalizeAddress, /localhost\|127\\\.0\\\.0\\\.1/)
  assert.match(normalizeAddress, /https:\/\/\$\{value\}/)
})

test('browser identity does not spoof Chrome client hints', () => {
  assert.match(userAgent, /Chrome\/\$\{chromeVersion\(\)\}/)
  assert.doesNotMatch(userAgent, /sec-ch-ua/)
  assert.doesNotMatch(userAgent, /Google Chrome/)
})

test('image-based themes are generated in the main process', () => {
  assert.match(browserContracts, /imageThemeRequestSchema/)
  assert.match(browserContracts, /savedBrowserThemeSchema/)
  assert.match(browserContracts, /savedThemes/)
  assert.match(browserContracts, /generateThemeFromImage: 'browser:settings:theme-from-image'/)
  assert.match(browserIpc, /generateThemeFromImage\(imageThemeRequestSchema\.parse\(raw\)\.source\)/)
  assert.match(imageTheme, /nativeImage/)
  assert.match(imageTheme, /net\.fetch/)
  assert.match(settingsPanel, /Apply theme/)
  assert.match(settingsPanel, /Save current/)
  assert.match(settingsPanel, /applySavedTheme/)
  assert.match(settingsRepository, /savedBrowserThemeSchema/)
})

test('startup config preloads saved browser theme before React renders', () => {
  assert.match(browserContracts, /startupConfigSchema/)
  assert.match(browserContracts, /defaultStartupConfig/)
  assert.match(browserContracts, /startupConfig: StartupConfig/)
  assert.match(startupConfigRepository, /app\.getPath\('userData'\)/)
  assert.match(startupConfigRepository, /startup-config\.json/)
  assert.match(startupConfigRepository, /safeParse/)
  assert.match(startupConfigRepository, /defaultStartupConfig/)
  assert.match(startupConfigRepository, /syncBrowserSettings\(browserSettings: BrowserSettings\)/)
  assert.doesNotMatch(startupConfigRepository, /token|password|cookie|secret|apiKey/i)
  assert.match(settingsRepository, /startupConfig\?: StartupConfigRepository/)
  assert.match(settingsRepository, /this\.startupConfig\?\.syncBrowserSettings\(settings\)/)
  assert.match(main, /new StartupConfigRepository\(\)/)
  assert.match(main, /startup\.syncBrowserSettings\(settings\.getBrowserSettings\(\)\)/)
  assert.match(main, /show: false/)
  assert.match(main, /backgroundColor: startupConfig\.browserSettings\.theme\.colors\.bgPrimary/)
  assert.match(main, /ready-to-show/)
  assert.match(main, /additionalArguments: \[`--stackly-startup-config=\$\{encodeURIComponent\(JSON\.stringify\(startupConfig\)\)\}`\]/)
  assert.match(preload, /readStartupConfig/)
  assert.match(preload, /process\.argv\.find/)
  assert.match(preload, /startupConfig: readStartupConfig\(\)/)
  assert.match(rendererMain, /applyStartupTheme\(\)[\s\S]*ReactDOM\.createRoot/)
  assert.match(startupTheme, /document\.documentElement/)
  assert.match(startupTheme, /root\.style\.setProperty/)
  assert.match(styles, /html \{[^}]*background: var\(--color-bg-primary\)/)
  assert.match(appRenderer, /startupConfig\(\)/)
  assert.match(appRenderer, /initialStartupConfig\.browserSettings/)
  assert.match(appRenderer, /applyStartupTheme\(\{ version: 1, browserSettings: saved \}\)/)
})

test('external browser fallback validates navigable URLs', () => {
  assert.match(browserIpc, /shell\.openExternal\(navigateSchema\.parse\(url\)\)/)
})

test('source control push avoids force push', () => {
  assert.match(gitService, /\.push\(\)/)
  assert.doesNotMatch(gitService, /--force|force-with-lease/)
})

test('git context service returns structured metadata without secrets or file contents', () => {
  assert.match(gitContracts, /gitContextSchema/)
  assert.match(gitContracts, /modifiedFiles/)
  assert.match(gitContracts, /stagedFiles/)
  assert.match(gitContextService, /class GitContextService/)
  assert.match(gitContextService, /gitContextSchema\.parse/)
  assert.match(gitContextService, /workspaceId/)
  assert.match(gitContextService, /remoteRepository: status\.githubRemote\?\.github/)
  assert.doesNotMatch(gitContextService, /authorEmail/)
  assert.doesNotMatch(gitContextService, /readFile|process\.env|token|secret|privateKey/i)
})

test('source code reader restricts project file access', () => {
  assert.match(gitContracts, /sourceCodeFileContentSchema/)
  assert.match(sourceCodeReader, /class SourceCodeReaderService/)
  assert.match(sourceCodeReader, /listProjectFiles/)
  assert.match(sourceCodeReader, /readProjectFile/)
  assert.match(sourceCodeReader, /realpath/)
  assert.match(sourceCodeReader, /isAbsolute\(path\).*includes\('\.\.'\)/s)
  assert.match(sourceCodeReader, /Symlink target is outside the repository/)
  assert.match(sourceCodeReader, /maxFileBytes/)
  assert.match(sourceCodeReader, /\.env/)
  assert.match(sourceCodeReader, /private\[-_\.\]\?key/)
})

test('github pull requests are listed through typed contracts', () => {
  assert.match(githubContracts, /githubPullRequestPageSchema/)
  assert.match(githubContracts, /listPullRequests: 'github:pull-requests:list'/)
  assert.match(githubProvider, /rest\.pulls\.list/)
})

test('github pull request details include commits files and checks', () => {
  assert.match(githubContracts, /githubPullRequestDetailSchema/)
  assert.match(githubContracts, /getPullRequest: 'github:pull-requests:get'/)
  assert.match(githubProvider, /rest\.pulls\.get/)
  assert.match(githubProvider, /rest\.pulls\.listCommits/)
  assert.match(githubProvider, /rest\.pulls\.listFiles/)
  assert.match(githubProvider, /rest\.checks\.listForRef/)
})

test('github pull requests can be created through explicit typed request', () => {
  assert.match(githubContracts, /githubPullRequestCreateRequestSchema/)
  assert.match(githubContracts, /createPullRequest: 'github:pull-requests:create'/)
  assert.match(githubProvider, /rest\.pulls\.create/)
  assert.match(githubProvider, /maintainer_can_modify: true/)
})

test('github issues are listed separately from pull requests', () => {
  assert.match(githubContracts, /githubIssuePageSchema/)
  assert.match(githubContracts, /listIssues: 'github:issues:list'/)
  assert.match(githubProvider, /rest\.issues\.listForRepo/)
  assert.match(githubProvider, /!issue\.pull_request/)
})

test('github actions workflow runs are listed without trigger controls', () => {
  assert.match(githubContracts, /githubActionsRunPageSchema/)
  assert.match(githubContracts, /listActionsRuns: 'github:actions:runs:list'/)
  assert.match(githubProvider, /rest\.actions\.listWorkflowRunsForRepo/)
  assert.match(githubProvider, /queued/)
  assert.doesNotMatch(githubProvider, /createWorkflowDispatch/)
})

test('github context service limits remote metadata and exposes no credentials', () => {
  assert.match(githubContracts, /githubContextSchema/)
  assert.match(githubContextService, /class GitHubContextService/)
  assert.match(githubContextService, /openPullRequests/)
  assert.match(githubContextService, /recentIssues/)
  assert.match(githubContextService, /latestWorkflowRuns/)
  assert.match(githubContextService, /perPage: 5/)
  assert.match(githubContextService, /GitHub is not connected/)
  assert.doesNotMatch(githubContextService, /token|credential|authorization/i)
})

test('persisted browser tabs are scoped by workspace', () => {
  assert.match(database, /PRIMARY KEY \(workspace_id, id\)/)
  assert.match(database, /PRAGMA user_version = 8/)
  assert.match(database, /ALTER TABLE tabs ADD COLUMN kind TEXT NOT NULL DEFAULT 'normal'/)
  assert.match(database, /CREATE TABLE device_canvas_layouts/)
  assert.match(database, /tab_id TEXT NOT NULL/)
  assert.match(database, /PRIMARY KEY \(workspace_id, tab_id\)/)
  assert.match(database, /CREATE TABLE navigation_history/)
  assert.match(database, /navigation_history_workspace_date/)
  assert.match(database, /REFERENCES workspaces\(id\) ON DELETE CASCADE/)
  assert.match(tabManager, /crypto\.randomUUID\(\)/)
  assert.match(browserContracts, /reorderTabs: 'browser:tabs:reorder'/)
  assert.match(browserIpc, /reorder\(tabOrderSchema\.parse\(ids\)\)/)
  assert.match(tabManager, /reorder\(ids: string\[\]\)/)
  assert.doesNotMatch(tabManager, /initialTabId/)
  assert.match(workspaceManager, /this\.activeWorkspaceId = id[\s\S]*this\.emitSnapshot\(\)[\s\S]*next\.tabs\.setWorkspaceVisible\(true\)/)
  assert.match(tabsStore, /snapshotWorkspaceId: string/)
  assert.match(tabsStore, /applySnapshot: \(snapshot, workspaceId = ''\) => set\(\{ \.\.\.snapshot, snapshotWorkspaceId: workspaceId \}\)/)
  assert.match(appRenderer, /tabsWorkspaceId = useTabsStore\(\(state\) => state\.snapshotWorkspaceId\)/)
  assert.match(appRenderer, /workspaceReady = Boolean\(activeWorkspace && activeWorkspace\.id === activeWorkspaceId && tabsWorkspaceId === activeWorkspaceId\)/)
  assert.match(appRenderer, /window\.devBrowser\.tabs\.getState\(\)[\s\S]*applySnapshot\(snapshot, activeWorkspaceId\)/)
  assert.match(appRenderer, /type MountedWorkspace = \{ workspace: Workspace; tabs: TabState\[\]; activeTabId: string \| null \}/)
  assert.match(appRenderer, /mountedWorkspaces, setMountedWorkspaces/)
  assert.match(appRenderer, /setMountedWorkspaces\(\(current\) => \(\{/)
  assert.match(appRenderer, /\[activeWorkspace\.id\]: \{ workspace: activeWorkspace, tabs, activeTabId \}/)
  assert.match(appRenderer, /Object\.values\(mountedWorkspaces\)\.map/)
  assert.match(appRenderer, /key=\{`\$\{record\.workspace\.id\}:\$\{tab\.id\}`\}/)
  assert.match(appRenderer, /workspaceId=\{record\.workspace\.id\}/)
  assert.match(appRenderer, /active=\{activeRecord && !devicesCanvas && !internalPage && !empty && tab\.id === record\.activeTabId\}/)
  assert.match(appRenderer, /type WorkspaceViewContext = \{ split: SplitState; viewportPresetByTab: Record<string, ViewportPreset> \}/)
  assert.match(appRenderer, /workspaceViewContexts = useRef<Record<string, WorkspaceViewContext>>\(\{\}\)/)
  assert.match(appRenderer, /saveWorkspaceViewContext\(\{ split: next \}\)/)
  assert.match(appRenderer, /saveWorkspaceViewContext\(\{ viewportPresetByTab: next \}\)/)
  assert.match(appRenderer, /workspaceViewContexts\.current\[activeWorkspaceId\] \?\? defaultWorkspaceViewContext\(\)/)
  assert.doesNotMatch(appRenderer, /setViewportPresetByTab\(\{\}\)[\s\S]*setSplit\(\{ environmentId: null, syncPath: true \}\)/)
})

test('browser content is rendered as DOM webview below React chrome', () => {
  assert.match(main, /webviewTag: true/)
  assert.match(appRenderer, /function BrowserWebview/)
  assert.match(appRenderer, /<webview/)
  assert.match(appRenderer, /setBrowserDomController/)
  assert.match(appRenderer, /tabs\.updateState/)
  assert.match(appRenderer, /stacklyTargetUrl/)
  assert.match(appRenderer, /stacklyLoadingUrl/)
  assert.match(appRenderer, /stacklyNavigationId/)
  assert.match(appRenderer, /view\.stop\(\)/)
  assert.match(appRenderer, /loadTargetUrl/)
  assert.match(appRenderer, /ERR_ABORTED/)
  assert.match(appRenderer, /did-fail-provisional-load/)
  assert.match(appRenderer, /navigationTarget/)
  assert.match(appRenderer, /delete webview\.dataset\.stacklyTargetUrl/)
  assert.match(appRenderer, /delete webview\.dataset\.stacklyLoadingUrl/)
  assert.match(appRenderer, /delete webview\.dataset\.stacklyNavigationId/)
  assert.match(appRenderer, /browser-load-error/)
  assert.match(appRenderer, /retryFailedNavigation/)
  assert.match(appRenderer, /Try again/)
  assert.match(appRenderer, /currentUrl === 'about:blank'/)
  assert.match(appRenderer, /is-hidden/)
  assert.match(browserContracts, /updateTabState: 'browser:tabs:update-state'/)
  assert.match(browserContracts, /setChromeOverlayOpen: 'browser:layout:set-chrome-overlay-open'/)
  assert.match(browserContracts, /setTooltipOpen: 'browser:layout:set-tooltip-open'/)
  assert.match(tabManager, /Map<string, TabState>/)
  assert.doesNotMatch(tabManager, /WebContentsView/)
  assert.match(tooltipLayer, /setTooltipOpen\(Boolean\(source\)\)/)
  assert.match(styles, /\.browser-webviews/)
  assert.match(styles, /\.browser-webviews\.is-hidden/)
  assert.match(styles, /\.browser-webview/)
  assert.match(styles, /\.browser-webviews\.is-hidden \{[^}]*visibility: hidden/)
  assert.match(styles, /\.browser-webview \{[^}]*display: none/)
  assert.match(styles, /\.browser-webview\.is-active \{[^}]*display: flex/)
  assert.match(styles, /\.browser-load-error/)
  assert.doesNotMatch(styles, /\.browser-webviews\.is-hidden \{[^}]*display: none/)
})

test('new-window requests are opened as internal browser tabs', () => {
  assert.match(browserContracts, /createTabRequestSchema/)
  assert.match(browserContracts, /tabKindSchema = z\.enum\(\['normal', 'device'\]\)/)
  assert.match(browserContracts, /tabStateUpdateSchema = z\.strictObject/)
  assert.match(browserContracts, /kind: tabKindSchema\.optional\(\)/)
  assert.doesNotMatch(browserContracts, /tabStateUpdateSchema = tabStateSchema\.partial\(\)/)
  assert.match(browserContracts, /create: \(url\?: string, active\?: boolean, kind\?: TabKind\) => Promise<string>/)
  assert.match(preload, /createTabRequestSchema\.parse\(\{ url, active, kind \}\)/)
  assert.match(preload, /ipcRenderer\.invoke\(browserChannels\.createTab/)
  assert.match(browserIpc, /createTabRequestSchema\.parse\(raw \?\? \{\}\)/)
  assert.match(browserIpc, /const url = request\.url \? navigateSchema\.parse\(request\.url\) : ''/)
  assert.match(browserIpc, /create\(url, false, request\.active, request\.kind\)/)
  assert.match(tabManager, /create\(url = '', muted = false, active = true, kind: TabKind = 'normal'\): string/)
  assert.match(tabManager, /if \(active\) this\.activeTabId = id/)
  assert.match(appRenderer, /type WebviewNewWindowEvent = Event & \{ url\?: string; disposition\?: string \}/)
  assert.match(appRenderer, /webview\.addEventListener\('new-window', newWindow\)/)
  assert.match(appRenderer, /window\.devBrowser\.tabs\.create\(event\.url, event\.disposition !== 'background-tab'\)/)
  assert.doesNotMatch(appRenderer, /tabs\.create\(\)\.then\(\(id\) => window\.devBrowser\.tabs\.updateState/)
  assert.match(appRenderer, /webview\.removeAttribute\('allowpopups'\)/)
  assert.doesNotMatch(appRenderer, /setAttribute\('allowpopups'/)
  assert.match(browserView, /setWindowOpenHandler\(\(\{ url, disposition \}\) =>/)
  assert.match(browserView, /destination\.protocol === 'http:' \|\| destination\.protocol === 'https:'/)
  assert.match(browserView, /onOpenUrl\(destination\.href, disposition !== 'background-tab'\)/)
  assert.match(browserView, /return \{ action: 'deny' \}/)
  assert.match(main, /did-attach-webview/)
  assert.match(main, /contents\.setWindowOpenHandler\(\(\{ url, disposition \}\) =>/)
  assert.match(main, /workspaces\.openUrlFromWebContents\(contents\.id, destination\.href, disposition !== 'background-tab'\)/)
  assert.match(workspaceManager, /openUrlFromWebContents\(webContentsId: number, url: string, active: boolean\): string \| null/)
  assert.match(workspaceManager, /workspace\.tabs\.tabIdForWebContents\(webContentsId\)/)
  assert.match(tabManager, /tabIdForWebContents\(webContentsId: number\): string \| null/)
  assert.match(deviceViewManager, /openUrlInTab: \(url: string, active: boolean\) => void = \(\) => \{\}/)
  assert.match(deviceViewManager, /const handle = createBrowserView\([\s\S]*this\.openUrlInTab[\s\S]*\)/)
  assert.match(workspaceManager, /let tabs: TabManager/)
  assert.match(workspaceManager, /new DeviceViewManager\(this\.window, workspaceSession, preserveNetworkLog, preserveConsoleLog, \(url, active\) => \{ tabs\.create\(url, false, active\) \}, \(tabId, state\) => \{/)
})

test('browser webviews keep a stable mount order across tab reorders', () => {
  assert.match(appRenderer, /webviewOrder/)
  assert.match(appRenderer, /new Map<string, string\[\]>\(\)/)
  assert.match(appRenderer, /function orderedTabs\(workspaceId: string, workspaceTabs: TabState\[\]\): TabState\[\]/)
  assert.match(appRenderer, /webviewOrder\.current\.get\(workspaceId\)\?\.filter/)
  assert.match(appRenderer, /if \(!order\.includes\(tab\.id\)\) order\.push\(tab\.id\)/)
  assert.match(appRenderer, /webviewOrder\.current\.set\(workspaceId, order\)/)
  assert.match(appRenderer, /orderedTabs\(record\.workspace\.id, record\.tabs\)\.filter\(\(tab\) => tab\.kind !== 'device'\)\.map/)
  assert.doesNotMatch(appRenderer, /tabs\.map\(\(tab\) => <BrowserWebview/)
})

test('workspace switches preserve mounted browser webviews without reload', () => {
  assert.match(appRenderer, /const viewKey = `\$\{workspaceId\}:\$\{tabId\}`/)
  assert.match(appRenderer, /register\(viewKey, webview\)/)
  assert.match(appRenderer, /register\(viewKey, null\)/)
  assert.match(appRenderer, /function isCurrentWorkspace\(\): boolean/)
  assert.match(appRenderer, /useWorkspacesStore\.getState\(\)\.activeWorkspaceId === workspaceId/)
  assert.match(appRenderer, /if \(!isCurrentWorkspace\(\)\) return/)
  assert.match(appRenderer, /const becameActive = active && !wasActive\.current/)
  assert.match(appRenderer, /if \(becameActive && current\) \{/)
  assert.match(appRenderer, /window\.devBrowser\.tabs\.updateState\(\{ id: tabId, url: current/)
  assert.match(appRenderer, /webviews\.current\.get\(`\$\{activeWorkspaceId\}:\$\{activeTabId\}`\)/)
  assert.match(appRenderer, /setBrowserDomController/)
  assert.doesNotMatch(appRenderer, /key=\{`\$\{activeWorkspace\.id\}:\$\{tab\.id\}`\}/)
})

test('renderer chrome uses explicit z-index layers above browser content', () => {
  for (const token of ['--z-browser-surface', '--z-shell-chrome', '--z-panel', '--z-popover', '--z-overlay', '--z-tooltip']) {
    assert.match(styles, new RegExp(`${token}:`))
  }
  assert.match(styles, /\.shell-toolbar \{[^}]*z-index: var\(--z-shell-chrome\)/)
  assert.match(styles, /\.tab-bar \{[^}]*z-index: var\(--z-shell-chrome\)/)
  assert.match(styles, /\.source-control-drawer \{[^}]*z-index: var\(--z-panel\)/)
  assert.match(styles, /\.palette-backdrop \{[^}]*z-index: var\(--z-overlay\)/)
  assert.match(styles, /\.settings-backdrop \{[^}]*z-index: var\(--z-overlay\)/)
  assert.match(styles, /\.app-tooltip \{[^}]*z-index: var\(--z-tooltip\)/)
})

test('command palette commands have centralized keyboard shortcuts', () => {
  for (const id of ['palette-toggle', 'new-tab', 'next-tab', 'previous-tab', 'reopen-closed-tab', 'close-tab', 'reload', 'capture-screenshot', 'connect-repository', 'toggle-dev-panel', 'open-network', 'open-console', 'open-history', 'open-settings']) {
    assert.match(shortcuts, new RegExp(`id: '${id}'`))
  }
  assert.match(shortcuts, /export function shortcutIdForKeyboardEvent/)
  assert.match(shortcuts, /export function acceleratorForShortcut/)
  assert.match(shortcuts, /platform === 'darwin' \? 'Cmd' : 'Ctrl'/)
  assert.match(shortcuts, /\{ id: 'next-tab', key: 'Tab', control: true \}/)
  assert.match(shortcuts, /\{ id: 'previous-tab', key: 'Tab', control: true, shift: true \}/)
  assert.match(shortcuts, /\{ id: 'reopen-closed-tab', key: 't', primary: true, shift: true \}/)
  assert.match(shortcuts, /\{ id: 'open-history', key: 'h', macKey: 'y', primary: true \}/)
  assert.match(shortcuts, /event\.key === 'ArrowRight'\) return 'next-tab'/)
  assert.match(shortcuts, /event\.key === 'ArrowLeft'\) return 'previous-tab'/)
  assert.match(shortcuts, /platform === 'darwin' \? shortcut\.macKey \?\? shortcut\.key : shortcut\.key/)
  assert.match(shortcuts, /!shortcut\.control && Boolean\(shortcut\.primary\) !== primaryPressed/)
  assert.match(commandRegistry, /function adjacentTabId/)
  assert.match(commandRegistry, /tabs\[\(index \+ direction \+ tabs\.length\) % tabs\.length\]/)
  assert.match(commandRegistry, /Next Tab/)
  assert.match(commandRegistry, /Previous Tab/)
  assert.match(commandRegistry, /window\.devBrowser\.tabs\.select\(id\)/)
  assert.match(commandRegistry, /Reopen Closed Tab/)
  assert.match(commandRegistry, /Open History/)
  assert.match(commandRegistry, /openHistory/)
  assert.match(commandRegistry, /window\.devBrowser\.tabs\.reopenClosed\(\)/)
  assert.match(commandRegistry, /shortcutId: ShortcutId/)
  assert.match(commandRegistry, /shortcut: string/)
  assert.match(commandRegistry, /function withShortcut/)
  assert.match(commandRegistry, /formatShortcut\(shortcut, platform\)/)
  assert.match(commandRegistry, /indexedShortcut\('workspace', index\)/)
  assert.match(commandRegistry, /indexedShortcut\('environment', index\)/)
  assert.match(commandPalette, /command\.shortcut && <kbd>\{command\.shortcut\}<\/kbd>/)
  assert.match(commandPalette, /const visibleCommands = useMemo\(\(\) => groups\.flatMap/)
  assert.match(commandPalette, /run\(visibleCommands\[activeIndex\]\)/)
  assert.match(commandPalette, /aria-activedescendant=\{visibleCommands\[activeIndex\]/)
  assert.match(commandPalette, /const index = visibleCommands\.indexOf\(command\)/)
  assert.doesNotMatch(commandPalette, /run\(matches\[activeIndex\]\)/)
  assert.match(browserContracts, /commandShortcut: 'browser:commands:shortcut'/)
  assert.match(browserContracts, /onShortcut: \(listener: \(shortcutId: string\) => void\) => \(\) => void/)
  assert.match(preload, /ipcRenderer\.on\(browserChannels\.commandShortcut, handler\)/)
  assert.match(commandShortcuts, /Menu\.setApplicationMenu/)
  assert.match(commandShortcuts, /shortcut\.id !== 'next-tab' && shortcut\.id !== 'previous-tab'/)
  assert.match(commandShortcuts, /accelerator: acceleratorForShortcut\(shortcut, process\.platform\)/)
  assert.match(commandShortcuts, /browserChannels\.commandShortcut/)
  assert.match(main, /installCommandShortcutMenu\(window\)/)
  assert.match(main, /contents\.on\('before-input-event'/)
  assert.match(main, /shortcutIdForKeyboardEvent/)
  assert.match(main, /browserChannels\.commandShortcut/)
  assert.match(appRenderer, /shortcutIdForKeyboardEvent\(event, shortcutPlatform\)/)
  assert.match(appRenderer, /target\?\.closest\('\.terminal-host, \.xterm'\)/)
  assert.match(appRenderer, /window\.devBrowser\.palette\.onShortcut\(runShortcut\)/)
  assert.match(appRenderer, /commands\.find\(\(item\) => item\.shortcutId === shortcutId\)/)
  assert.match(appRenderer, /lastShortcutRun\.current/)
  assert.doesNotMatch(appRenderer, /ctrlKey\) && event\.shiftKey && event\.key\.toLowerCase\(\) === 'p'/)
})

test('tab bar pointer drag scrolls horizontally without reordering tabs', () => {
  assert.match(tabBar, /scrollRef/)
  assert.match(tabBar, /stripRef/)
  assert.match(tabBar, /Math\.abs\(deltaX\) < 5/)
  assert.match(tabBar, /window\.addEventListener\('mousemove'/)
  assert.match(tabBar, /window\.removeEventListener\('mousemove'/)
  assert.match(tabBar, /className="tab-strip"/)
  assert.match(tabBar, /function startButtonDrag/)
  assert.match(tabBar, /function targetIndexForClientX/)
  assert.match(tabBar, /function applySiblingTransforms/)
  assert.match(tabBar, /function clearTabTransforms/)
  assert.match(tabBar, /function tabMovementDistance/)
  assert.match(tabBar, /function suppressNextClick/)
  assert.match(tabBar, /function stopSuppressedClick/)
  assert.match(tabBar, /function shouldIgnoreClick/)
  assert.match(tabBar, /function closeTabOnMiddleClick/)
  assert.match(tabBar, /event\.button !== 1/)
  assert.match(tabBar, /onMouseUp=\{\(event\) => closeTabOnMiddleClick\(tab\.id, event\)\}/)
  assert.match(tabBar, /function reorderedIds/)
  assert.doesNotMatch(tabBar, /dragOrder|orderedTabs|setDragOrder/)
  assert.match(tabBar, /window\.devBrowser\.tabs\.reorder/)
  assert.match(tabBar, /window\.addEventListener\('click', stopSuppressedClick, \{ capture: true, once: true \}\)/)
  assert.match(tabBar, /stopImmediatePropagation/)
  assert.match(tabBar, /tab-item--reordering/)
  assert.match(tabBar, /<div ref=\{stripRef\} className="tab-strip">[\s\S]*className="tab-new"[\s\S]*<\/div>/)
  assert.match(tabBar, /style\.transform = `translateX/)
  assert.match(tabBar, /onMouseDownCapture=\{\(event\) => startButtonDrag\(tab\.id, event\)\}/)
  assert.match(tabBar, /draggable=\{false\}/)
  assert.doesNotMatch(tabBar, /onPointerDownCapture|onPointerMove=\{|setPointerCapture|releasePointerCapture/)
  assert.match(tabBar, /onClickCapture=\{maybeSuppressClick\}/)
  assert.match(tabBar, /if \(shouldIgnoreClick\(event\)\) return/)
  assert.match(tabBar, /suppressClickRef/)
  assert.doesNotMatch(tabBar, /closest\('\.tab-close'\)/)
  assert.doesNotMatch(tabBar, /draggable=\{true\}|draggable="true"/)
  assert.doesNotMatch(tabBar, /onDrop|onDragStart|dataTransfer/)
  assert.match(styles, /\.tab-list \{[^}]*overflow: hidden/)
  assert.match(styles, /\.tab-list \{[^}]*flex: 1 1 0/)
  assert.match(styles, /\.tab-strip \{[^}]*width: max-content/)
  assert.match(styles, /\.tab-strip \{[^}]*will-change: transform/)
  assert.match(styles, /\.tab-list \{[^}]*-webkit-app-region: no-drag/)
  assert.match(styles, /\.tab-list \{[^}]*user-select: none/)
  assert.match(styles, /\.tab-select span, \.tab-select svg, \.tab-audio svg, \.tab-close svg \{[^}]*-webkit-user-drag: none/)
  assert.match(styles, /\.tab-list\.is-reordering/)
  assert.match(styles, /\.tab-item--reordering/)
  assert.match(styles, /\.tab-item--reordering \{[^}]*transition: none/)
  assert.match(styles, /\.tab-item \{[^}]*transition: transform 90ms ease/)
  assert.doesNotMatch(styles, /is-panning-left|is-panning-right|#2563eb|#16a34a/)
  assert.doesNotMatch(styles, /tab-item--drop|tab-item--dragging/)
})

test('tabs support per-tab mute and reopening recently closed tabs', () => {
  assert.match(browserContracts, /isMuted: z\.boolean\(\)\.default\(false\)/)
  assert.match(browserContracts, /isAudible: z\.boolean\(\)\.default\(false\)/)
  assert.match(browserContracts, /reopenClosedTab: 'browser:tabs:reopen-closed'/)
  assert.match(browserContracts, /setTabAudioMuted: 'browser:tabs:set-audio-muted'/)
  assert.match(browserContracts, /reopenClosed: \(\) => Promise<string \| null>/)
  assert.match(browserContracts, /setAudioMuted: \(id: string, muted: boolean\) => Promise<void>/)
  assert.match(preload, /reopenClosed: async \(\) => tabIdSchema\.nullable\(\)\.parse/)
  assert.match(preload, /setAudioMuted: async \(id, muted\) =>/)
  assert.match(browserIpc, /browserChannels\.reopenClosedTab/)
  assert.match(browserIpc, /getWorkspaces\(event\)\.reopenClosedTab\(\)/)
  assert.match(browserIpc, /browserChannels\.setTabAudioMuted/)
  assert.match(browserIpc, /getWorkspaces\(event\)\.setTabAudioMuted\(tabIdSchema\.parse\(id\), muted\)/)
  assert.match(tabManager, /isMuted: muted/)
  assert.match(tabManager, /isAudible: false/)
  assert.match(tabManager, /setAudioMuted\(tabId: string, muted: boolean\)/)
  assert.match(tabManager, /target\.contents\.setAudioMuted\(tab\.isMuted\)/)
  assert.match(tabManager, /contents\.on\('audio-state-changed', onAudioStateChanged\)/)
  assert.match(workspaceManager, /type ClosedTabRecord/)
  assert.match(workspaceManager, /private readonly closedTabs: ClosedTabRecord\[\] = \[\]/)
  assert.match(workspaceManager, /rememberClosedTab\(data\.id, tab\)/)
  assert.match(workspaceManager, /this\.closedTabs\.unshift/)
  assert.match(workspaceManager, /this\.closedTabs\.splice\(20\)/)
  assert.match(workspaceManager, /reopenClosedTab\(\): string \| null/)
  assert.match(workspaceManager, /if \(record\.workspaceId !== this\.activeWorkspaceId\) this\.select\(record\.workspaceId\)/)
  assert.match(workspaceManager, /workspace\.tabs\.create\(record\.url, record\.isMuted, true, record\.kind\)/)
  assert.match(workspaceManager, /setTabAudioMuted\(tabId: string, muted: boolean\)/)
  assert.match(workspaceManager, /workspace\.deviceViews\.setAudioMutedForTab\(tabId, muted\)/)
  assert.match(deviceViewManager, /setAudioMutedForTab\(tabId: string, muted: boolean\)/)
  assert.match(deviceViewManager, /webContents\.setAudioMuted\(muted\)/)
  assert.match(tabBar, /Volume2/)
  assert.match(tabBar, /VolumeX/)
  assert.match(tabBar, /tab-audio/)
  assert.match(tabBar, /Mutar guia/)
  assert.match(tabBar, /Ativar som da guia/)
  assert.match(tabBar, /Reabrir guia fechada/)
  assert.match(tabBar, /window\.devBrowser\.tabs\.setAudioMuted\(tabId, muted\)/)
  assert.match(tabBar, /window\.devBrowser\.tabs\.reopenClosed\(\)/)
  assert.match(styles, /\.tab-context-menu/)
  assert.match(styles, /\.tab-audio/)
})

test('navigation history is scoped to the active workspace', () => {
  assert.match(browserContracts, /navigationHistoryEntrySchema/)
  assert.match(browserContracts, /navigationHistoryVisitSchema/)
  for (const channel of ['getHistory', 'recordHistory', 'removeHistoryEntry', 'clearHistory']) assert.match(browserContracts, new RegExp(`${channel}: 'browser:history:`))
  assert.match(database, /CREATE TABLE navigation_history/)
  assert.match(database, /workspace_id TEXT NOT NULL REFERENCES workspaces\(id\) ON DELETE CASCADE/)
  assert.match(database, /navigation_history_workspace_date/)
  assert.match(workspaceRepository, /listHistory\(workspaceId: string, query = ''\): NavigationHistoryEntry\[\]/)
  assert.match(workspaceRepository, /recordHistory\(workspaceId: string, visit: NavigationHistoryVisit\): void/)
  assert.match(workspaceRepository, /last\?\.url === url/)
  assert.match(workspaceRepository, /DELETE FROM navigation_history WHERE workspace_id = \? AND id = \?/)
  assert.match(workspaceRepository, /DELETE FROM navigation_history WHERE workspace_id = \?/)
  assert.match(workspaceManager, /private readonly historyKeys = new Map<string, string>\(\)/)
  assert.match(workspaceManager, /recordTabsHistory\(data\.id, snapshot\)/)
  assert.match(workspaceManager, /recordHistoryVisit\(data\.id, `device:\$\{tabId\}`/)
  assert.match(workspaceManager, /this\.repository\.recordHistory\(workspaceId, parsed\.data\)/)
  assert.match(workspaceManager, /destination\.protocol === 'http:' \|\| destination\.protocol === 'https:'/)
  assert.match(deviceViewManager, /onVisit: \(tabId: string, state: NavigationState\) => void = \(\) => \{\}/)
  assert.match(deviceViewManager, /this\.onVisit\(record\.tabId, navigationState\)/)
  assert.match(browserIpc, /browserChannels\.getHistory/)
  assert.match(browserIpc, /navigationHistoryVisitSchema\.parse\(raw\)/)
  assert.match(preload, /history: \{/)
  assert.match(preload, /navigationHistoryEntrySchema\.array\(\)\.parse/)
  assert.match(preload, /browserChannels\.recordHistory/)
  assert.match(appRenderer, /HistoryPanel/)
  assert.match(appRenderer, /onOpenHistory/)
  assert.match(workspaceManager, /recordHistoryVisit\(data\.id, `device:\$\{tabId\}`/)
  assert.match(historyPanel, /Search history/)
  assert.match(historyPanel, /window\.devBrowser\.history\.get/)
  assert.match(historyPanel, /window\.devBrowser\.tabs\.create\(entry\.url, true\)/)
  assert.match(historyPanel, /window\.devBrowser\.history\.remove\(id\)/)
  assert.match(historyPanel, /window\.devBrowser\.history\.clear\(\)/)
  assert.match(styles, /\.history-backdrop/)
  assert.match(styles, /\.history-entry/)
})

test('devices canvas runs outside the responsive toolbar', () => {
  assert.match(browserContracts, /devices-canvas/)
  assert.doesNotMatch(deviceToolbar, /Devices Canvas/)
  assert.match(appRenderer, /showDeviceToolbar=\{devPanelOpen && browserSettings\.features\.showDeviceToolbar && activeTab\?\.kind !== 'device'\}/)
  assert.match(appRenderer, /constrainedViewport = !devicesCanvas && !internalPage && !empty && preset !== 'responsive'/)
  assert.match(appRenderer, /' is-constrained'/)
  assert.match(styles, /\.browser-webviews\.is-constrained/)
  assert.match(styles, /--stackly-viewport-width/)
  assert.match(appRenderer, /function DevicesCanvas/)
  assert.match(appRenderer, /function CanvasToolbar/)
  assert.match(appRenderer, /function CanvasViewport/)
  assert.match(appRenderer, /function DevicesCanvasEmptyState/)
  assert.match(appRenderer, /function AddDevicePopover/)
  assert.match(appRenderer, /function DeviceFrame/)
  assert.match(appRenderer, /deviceSettingsSchema/)
  assert.match(appRenderer, /function DeviceSettingsPopover/)
  assert.match(appRenderer, /function deviceEnvironmentUrl/)
  assert.match(appRenderer, /base\.pathname = current\.pathname/)
  assert.match(appRenderer, /base\.search = current\.search/)
  assert.match(appRenderer, /base\.hash = current\.hash/)
  assert.match(appRenderer, /type DevicesCanvasLayout/)
  assert.match(appRenderer, /const hydrated = useRef\(false\)/)
  assert.match(appRenderer, /lastSavedLayout/)
  assert.match(appRenderer, /window\.devBrowser\.devices\.getLayout\(tab\.id\)/)
  assert.match(appRenderer, /window\.devBrowser\.devices\.saveLayout\(tab\.id, layout\)/)
  assert.match(appRenderer, /mirrorActiveLayout\(devices, selectedDeviceId\)/)
  assert.match(appRenderer, /setZoom\(layout\.zoom\)/)
  assert.match(appRenderer, /setPan\(layout\.pan\)/)
  assert.match(appRenderer, /setSyncNavigation\(layout\.syncNavigation\)/)
  assert.match(appRenderer, /setSyncNavigation\(false\)/)
  assert.match(appRenderer, /syncNavigation/)
  assert.match(appRenderer, /function deviceRouteDestination/)
  assert.match(appRenderer, /const handleDeviceNavigate = useCallback/)
  assert.match(appRenderer, /if \(!syncNavigation\) return/)
  assert.match(appRenderer, /deviceRouteDestination\(device\.url, url\)/)
  assert.match(appRenderer, /selectedDeviceId/)
  assert.match(appRenderer, /selectedDevice/)
  assert.match(appRenderer, /window\.devBrowser\.devices\.setDevToolsTarget\(targetTabId, targetDeviceId\)/)
  assert.match(appRenderer, /boundDevPanelTargetKey/)
  assert.match(appRenderer, /setBoundDevPanelTargetKey\(''\)/)
  assert.match(appRenderer, /\.then\(\(\) => \{ if \(!cancelled\) setBoundDevPanelTargetKey\(devPanelTargetKey\) \}\)/)
  assert.match(appRenderer, /const devPanelTargetAvailable = viewportPreset !== 'devices-canvas' \|\| Boolean\(activeTabId && selectedDeviceId\)/)
  assert.match(appRenderer, /const devPanelTargetReady = boundDevPanelTargetKey === devPanelTargetKey/)
  assert.match(appRenderer, /devPanelTargetLabel/)
  assert.match(appRenderer, /devPanelTargetKey/)
  assert.match(appRenderer, /targetAvailable=\{devPanelTargetAvailable\}/)
  assert.match(appRenderer, /targetReady=\{devPanelTargetReady\}/)
  assert.match(devPanel, /targetLabel/)
  assert.match(devPanel, /targetAvailable/)
  assert.match(devPanel, /targetReady/)
  assert.match(devPanel, /const needsChromiumTarget = activePanel === 'elements' \|\| activePanel === 'errors' \|\| activePanel === 'network' \|\| activePanel === 'console' \|\| activePanel === 'storage'/)
  assert.match(devPanel, /needsChromiumTarget && !targetAvailable/)
  assert.match(devPanel, /needsChromiumTarget && !targetReady/)
  assert.match(devPanel, /Binding Dev Panel target/)
  assert.match(devPanel, /Select a Chromium target to inspect/)
  assert.match(devPanel, /Target: \{targetLabel\}/)
  assert.match(styles, /\.dev-panel-empty-target/)
  assert.match(appRenderer, /window\.setTimeout\(\(\) => \{/)
  assert.match(appRenderer, /z\.number\(\)\.int\(\)\.min\(240\)\.max\(2560\)/)
  assert.match(appRenderer, /name: z\.string\(\)\.trim\(\)\.min\(1\)\.max\(60\)/)
  assert.match(appRenderer, /Viewport Width/)
  assert.match(appRenderer, /Viewport Height/)
  assert.match(appRenderer, /Orientation/)
  assert.match(appRenderer, /Environment/)
  assert.match(appRenderer, /environmentId/)
  assert.match(appRenderer, /Use dimensões entre 240 e 2560/)
  assert.match(appRenderer, /deviceEnvironmentUrl\(device\.url, environment\)/)
  assert.match(appRenderer, /environment\.kind === 'production'/)
  assert.match(appRenderer, /device-frame-environment/)
  assert.match(devicePresets, /category: 'Custom'/)
  assert.match(appRenderer, /<webview ref=\{webviewRef\} className="device-frame-webview"/)
  assert.match(appRenderer, /src=\{webviewSource\(device\.url\)\}/)
  assert.match(appRenderer, /partition=\{partition\}/)
  assert.match(appRenderer, /webview\.removeAttribute\('allowpopups'\)/)
  assert.match(appRenderer, /webviewRef\.current\?\.reload\(\)/)
  assert.match(appRenderer, /capturePage\?: \(\) => Promise<\{ toDataURL: \(\) => string \}>/)
  assert.match(appRenderer, /view\.capturePage\(\)/)
  assert.match(appRenderer, /anchor\.download = `stackly-\$\{id\}\.png`/)
  assert.doesNotMatch(appRenderer, /window\.devBrowser\.devices\.navigateView/)
  assert.doesNotMatch(appRenderer, /window\.devBrowser\.devices\.captureScreenshot\(activeTabId, id\)/)
  assert.match(appRenderer, /function DevicesCanvas\(\{ active, currentUrl, tab, workspace, onResponsive \}/)
  assert.match(appRenderer, /useState<VirtualDevice\[\]>\(\[\]\)/)
  assert.match(appRenderer, /devices-canvas\$\{active \? '' : ' is-hidden'\}/)
  assert.match(appRenderer, /filter\(\(tab\) => tab\.kind === 'device'\)/)
  assert.match(appRenderer, /<DevicesCanvas key=\{`\$\{record\.workspace\.id\}:\$\{tab\.id\}`\} active=\{activeSurface\}/)
  assert.match(appRenderer, /filter\(\(tab\) => tab\.kind !== 'device'\)/)
  assert.match(styles, /\.devices-canvas\.is-hidden/)
  assert.match(appRenderer, /Independent/)
  assert.match(appRenderer, /Sync Navigation/)
  assert.match(appRenderer, /onSyncNavigationChange/)
  assert.match(appRenderer, /device-load-error/)
  assert.match(appRenderer, /retryDeviceWebview/)
  assert.match(styles, /\.device-load-error/)
  assert.doesNotMatch(appRenderer, /pendingBoundsSync/)
  assert.doesNotMatch(appRenderer, /lastBoundsSignature/)
  assert.doesNotMatch(appRenderer, /canvasPan\.x, canvasPan\.y/)
  assert.doesNotMatch(appRenderer, /canvasPan=\{pan\}/)
  assert.match(appRenderer, /function reloadDeviceWebview/)
  assert.match(appRenderer, /function rotateDevice/)
  assert.match(appRenderer, /orientation: device\.orientation === 'portrait' \? 'landscape' : 'portrait'/)
  assert.match(appRenderer, /aria-label=\{`Reload \$\{device\.name\}`\}/)
  assert.match(appRenderer, /aria-label=\{`Rotate \$\{device\.name\}`\}/)
  assert.match(appRenderer, /aria-label=\{`Capture screenshot \$\{device\.name\}`\}/)
  assert.match(appRenderer, /aria-label=\{`Settings \$\{device\.name\}`\}/)
  assert.match(appRenderer, /Capture Screenshot/)
  assert.match(appRenderer, /function captureDeviceScreenshot/)
  assert.match(appRenderer, /view\.capturePage\(\)\.then/)
  assert.match(appRenderer, /anchor\.href = image\.toDataURL\(\)/)
  assert.match(appRenderer, /tabId={activeTabId}/)
  assert.match(appRenderer, /deviceViewportSize/)
  assert.match(appRenderer, /function deviceViewportVisualSize/)
  assert.match(appRenderer, /baseMax = device\.type === 'tablet' \? 340 : 240/)
  assert.match(appRenderer, /device\.displayScale/)
  assert.match(appRenderer, /function startResize/)
  assert.match(appRenderer, /function moveResize/)
  assert.match(appRenderer, /function stopResize/)
  assert.match(appRenderer, /onResize\(device\.id, nextScale\)/)
  assert.match(appRenderer, /setPointerCapture/)
  assert.match(appRenderer, /releasePointerCapture/)
  assert.match(appRenderer, /updateLocalPosition/)
  assert.match(appRenderer, /setClampedZoom/)
  assert.match(appRenderer, /Math\.min\(2, Math\.max\(0\.25/)
  assert.match(appRenderer, /spacePressed/)
  assert.match(appRenderer, /setPan/)
  assert.match(appRenderer, /const middleButton = event\.button === 1/)
  assert.match(appRenderer, /const spaceDrag = event\.button === 0 && spacePressed/)
  assert.match(appRenderer, /event\.preventDefault\(\)/)
  assert.match(appRenderer, /function stopMiddleClick/)
  assert.match(appRenderer, /onAuxClick=\{stopMiddleClick\}/)
  assert.doesNotMatch(appRenderer, /onWheel=\{wheelPan\}/)
  assert.match(appRenderer, /function resetView/)
  assert.match(appRenderer, /function fitToScreen/)
  assert.match(appRenderer, /function deviceBounds/)
  assert.match(appRenderer, /function visualDeviceFrameSize/)
  assert.match(appRenderer, /Fit to Screen/)
  assert.match(appRenderer, /onFitToScreen/)
  assert.match(appRenderer, /viewportRef/)
  assert.match(appRenderer, /const margin = 64/)
  assert.match(appRenderer, /availableWidth \/ bounds\.width/)
  assert.match(appRenderer, /availableHeight \/ bounds\.height/)
  assert.match(appRenderer, /setZoom\(Number\(nextZoom\.toFixed\(2\)\)\)/)
  assert.match(appRenderer, /setPan\(\{\s*x: Math\.round\(\(viewport\.clientWidth - bounds\.width \* nextZoom\) \/ 2 - bounds\.x \* nextZoom\)/s)
  assert.match(appRenderer, /Reset View/)
  assert.match(appRenderer, /window\.addEventListener\('keydown', updateSpace\)/)
  assert.match(appRenderer, /event\.code !== 'Space'/)
  assert.match(appRenderer, /function startPan/)
  assert.match(appRenderer, /function movePan/)
  assert.match(appRenderer, /function stopPan/)
  assert.match(appRenderer, /transform: `translate\(\$\{pan\.x\}px, \$\{pan\.y\}px\) scale\(\$\{zoom\}\)`/)
  assert.match(appRenderer, /\(event\.clientX - current\.pointerX\) \/ zoom/)
  assert.match(appRenderer, /onPointerDown=\{startDrag\}/)
  assert.match(appRenderer, /Preview your application across multiple devices\./)
  assert.match(appRenderer, /Add Device/)
  assert.match(appRenderer, /instantiateDeviceFromPreset/)
  assert.match(appRenderer, /removeLocalDevice/)
  assert.match(appRenderer, /onPresetChange\('responsive'\)/)
  assert.match(appRenderer, /preset === 'devices-canvas'/)
  assert.match(appRenderer, /activeTab\?\.kind === 'device' \? 'devices-canvas'/)
  assert.match(appRenderer, /activeTab\?\.kind === 'device'/)
  assert.match(appRenderer, /device-frame-address/)
  assert.match(tabBar, /createTab\('device'\)/)
  assert.match(tabBar, /Nova aba Device/)
  assert.match(appRenderer, /viewportPresetByTab/)
  assert.match(appRenderer, /viewportPresetByTab\[activeTabId\] \?\? 'responsive'/)
  assert.match(appRenderer, /\[activeTabId\]: preset/)
  assert.match(appRenderer, /setViewportPresetByTab\(context\.viewportPresetByTab\)/)
  assert.match(styles, /\.devices-canvas-toolbar/)
  assert.match(styles, /\.devices-canvas \{[^}]*background: var\(--color-bg-primary\)/)
  assert.match(styles, /\.devices-canvas-viewport/)
  assert.match(styles, /\.devices-canvas-viewport \{[^}]*background-color: var\(--color-bg-primary\)/)
  assert.match(styles, /\.devices-canvas-viewport \{[^}]*radial-gradient\(circle/)
  assert.match(styles, /\.devices-canvas-viewport \{[^}]*background-size: 24px 24px/)
  assert.match(styles, /\.devices-canvas-viewport\.is-space-panning/)
  assert.match(styles, /\.devices-canvas-viewport\.is-panning/)
  assert.match(styles, /\.devices-canvas-world/)
  assert.match(styles, /\.devices-sync-controls/)
  assert.match(styles, /\.devices-sync-controls button\.is-active/)
  assert.match(styles, /\.devices-zoom-controls/)
  assert.match(styles, /\.dev-panel-target/)
  assert.match(styles, /\.devices-canvas-empty/)
  assert.match(styles, /\.devices-add-popover/)
  assert.match(styles, /\.device-frame/)
  assert.match(styles, /\.device-frame-handle/)
  assert.match(styles, /\.device-frame-handle:active/)
  assert.match(styles, /\.device-frame-controls/)
  assert.match(styles, /\.device-frame-controls button/)
  assert.match(styles, /\.device-frame-controls button:disabled/)
  assert.match(styles, /\.device-frame-controls \{[^}]*position: absolute/)
  assert.match(styles, /\.device-frame-controls \{[^}]*right: 6px/)
  assert.match(styles, /\.device-frame-controls \{[^}]*justify-items: center/)
  assert.match(styles, /\.device-frame-controls \{[^}]*width: 32px/)
  assert.match(styles, /\.device-frame-controls \{[^}]*grid-auto-rows: 28px/)
  assert.match(styles, /\.device-frame-controls button \{[^}]*margin: 0 auto/)
  assert.match(styles, /\.device-frame-controls button \{[^}]*padding: 0/)
  assert.match(styles, /\.device-frame-controls \{[^}]*border: 1px solid/)
  assert.match(styles, /\.device-frame-controls \{[^}]*var\(--color-bg-primary\)/)
  assert.match(styles, /\.device-frame-handle strong \{[^}]*color: var\(--color-text-primary\)/)
  assert.match(styles, /\.device-frame-address/)
  assert.match(styles, /\.device-frame \{[^}]*grid-template-rows: 36px 28px minmax\(0, 1fr\)/)
  assert.match(styles, /\.device-frame-body \{[^}]*padding: 4px 44px 12px 10px/)
  assert.match(styles, /\.device-frame-screen/)
  assert.match(styles, /\.device-frame-screen \{[^}]*border: 0/)
  assert.match(styles, /\.device-frame-screen \{[^}]*background: transparent/)
  assert.match(styles, /\.device-frame-resize/)
  assert.match(styles, /cursor: nwse-resize/)
  assert.match(styles, /\.device-frame-environment/)
  assert.match(styles, /\.device-frame-environment\.is-production/)
  assert.match(styles, /\.device-settings-popover/)
  assert.match(styles, /\.device-settings-popover input/)
  assert.match(styles, /\.device-settings-popover button\[type="submit"\]/)
  assert.match(styles, /\.device-frame-viewport/)
  assert.match(styles, /#343447/)
  assert.match(styles, /#57536D/i)
  assert.match(styles, /#C58FA9/i)
})

test('devices canvas store models virtual devices', () => {
  for (const field of ['id', 'name', 'type', 'viewportWidth', 'viewportHeight', 'x', 'y', 'orientation', 'displayScale', 'url', 'environmentId', 'isSelected', 'zIndex']) {
    assert.match(devicesCanvasStore, new RegExp(`${field}:`))
  }
  for (const operation of ['addDevice', 'removeDevice', 'selectDevice', 'updateDevice', 'updatePosition', 'replaceLayout', 'clearDevices']) {
    assert.match(devicesCanvasStore, new RegExp(`${operation}:`))
  }
  assert.match(devicesCanvasStore, /crypto\.randomUUID\(\)/)
  assert.match(devicesCanvasStore, /nextZIndex/)
  assert.match(devicesCanvasStore, /promotedZIndex/)
  assert.match(devicesCanvasStore, /mobile.*tablet.*custom/s)
  assert.match(devicesCanvasStore, /portrait.*landscape/s)
})

test('devices canvas exposes a typed preset catalog', () => {
  for (const category of ['Mobile', 'Tablet', 'Custom']) assert.match(devicePresets, new RegExp(category))
  for (const preset of ['Small Phone', 'Large Phone', 'Small Tablet', 'Large Tablet', 'Custom']) assert.match(devicePresets, new RegExp(preset))
  for (const field of ['id', 'name', 'type', 'viewportWidth', 'viewportHeight', 'deviceScaleFactor']) {
    assert.match(devicePresets, new RegExp(`${field}:`))
  }
  assert.match(devicePresets, /instantiateDeviceFromPreset/)
  assert.match(devicePresets, /devicePresetsByCategory/)
  assert.doesNotMatch(devicePresets, /viewportWidth: -|viewportHeight: -|deviceScaleFactor: -/)
})

test('device canvas has a main-process WebContentsView lifecycle manager', () => {
  assert.match(browserContracts, /deviceViewDescriptorSchema/)
  assert.match(browserContracts, /deviceDevToolsTargetSchema/)
  assert.match(browserContracts, /devicesCanvasLayoutSchema/)
  assert.match(browserContracts, /syncNavigation: z\.boolean\(\)\.default\(false\)/)
  assert.match(browserContracts, /displayScale: z\.number\(\)\.min\(0\.55\)\.max\(3\)\.default\(1\)/)
  assert.match(browserContracts, /persistedCanvasDeviceSchema/)
  assert.match(browserContracts, /getDevicesCanvasLayout: 'browser:devices-canvas:get-layout'/)
  assert.match(browserContracts, /saveDevicesCanvasLayout: 'browser:devices-canvas:save-layout'/)
  assert.match(browserContracts, /viewport: z\.strictObject/)
  assert.match(browserContracts, /scaleFactor: z\.number\(\)\.positive\(\)/)
  assert.match(browserContracts, /zIndex: z\.number\(\)\.int\(\)\.nonnegative\(\)\.default\(0\)/)
  assert.match(browserContracts, /deviceViewSnapshotSchema/)
  assert.match(browserContracts, /ensureDeviceView: 'browser:devices:ensure-view'/)
  assert.match(browserContracts, /removeDeviceView: 'browser:devices:remove-view'/)
  assert.match(browserContracts, /reloadDeviceView: 'browser:devices:reload-view'/)
  assert.match(browserContracts, /captureDeviceScreenshot: 'browser:devices:capture-screenshot'/)
  assert.match(browserContracts, /setDeviceViewsVisible: 'browser:devices:set-visible'/)
  assert.match(browserContracts, /setDeviceViewVisible: 'browser:devices:set-view-visible'/)
  assert.match(browserContracts, /setDeviceDevToolsTarget: 'browser:devices:set-devtools-target'/)
  assert.match(browserContracts, /setDevicesNavigationSync: 'browser:devices-canvas:set-navigation-sync'/)
  assert.match(browserContracts, /ensureView: \(descriptor: DeviceViewDescriptor\) => Promise<DeviceViewSnapshot>/)
  assert.match(browserContracts, /captureScreenshot: \(tabId: string, deviceId: string\) => Promise<ScreenshotResult>/)
  assert.match(browserContracts, /setDevToolsTarget: \(tabId: string \| null, deviceId: string \| null\) => Promise<void>/)
  assert.match(browserContracts, /DeviceViewDescriptor/)
  assert.match(browserContracts, /DeviceViewSnapshot/)
  assert.match(deviceViewManager, /class DeviceViewManager/)
  assert.match(deviceViewManager, /new Map<string, DeviceViewRecord>/)
  assert.match(deviceViewManager, /deviceId: string/)
  assert.match(deviceViewManager, /tabId: string/)
  assert.match(deviceViewManager, /url: string/)
  assert.match(deviceViewManager, /viewport: DeviceViewDescriptor\['viewport'\]/)
  assert.match(deviceViewManager, /zIndex: number/)
  assert.match(deviceViewManager, /WebContentsView/)
  assert.match(deviceViewManager, /browserSession: Session/)
  assert.match(deviceViewManager, /createBrowserView/)
  assert.match(deviceViewManager, /ensureView\(descriptor: DeviceViewDescriptor\)/)
  assert.match(deviceViewManager, /deviceViewDescriptorSchema\.parse\(descriptor\)/)
  assert.match(deviceViewManager, /webContents\.loadURL\(url\)/)
  assert.match(deviceViewManager, /Failed to load device view/)
  assert.match(deviceViewManager, /function sameBounds/)
  assert.match(deviceViewManager, /if \(sameBounds\(record\.bounds, bounds\)\) return/)
  assert.match(deviceViewManager, /existing\.zIndex !== data\.zIndex/)
  assert.match(deviceViewManager, /reorderDeviceViewsForTab\(data\.tabId\)/)
  assert.match(deviceViewManager, /reorderDeviceViewsForTab\(tabId: string\)/)
  assert.match(deviceViewManager, /sort\(\(left, right\) => left\.zIndex - right\.zIndex\)/)
  assert.match(deviceViewManager, /contentView\.removeChildView\?\.\(record\.handle\.view\)/)
  assert.match(deviceViewManager, /this\.window\.contentView\.addChildView\(record\.handle\.view\)/)
  assert.match(deviceViewManager, /setVisibleForTab/)
  assert.match(deviceViewManager, /visibleTabId: string \| null/)
  assert.match(deviceViewManager, /workspaceVisible = false/)
  assert.match(deviceViewManager, /browserOverlayOpen = false/)
  assert.match(deviceViewManager, /setBrowserOverlayOpen\(open: boolean\)/)
  assert.match(deviceViewManager, /this\.browserOverlayOpen = open/)
  assert.match(deviceViewManager, /applyVisibility\(\): void/)
  assert.match(deviceViewManager, /const activeTabId = this\.canShowViews\(\) \? this\.visibleTabId : null/)
  assert.match(deviceViewManager, /record\.handle\.view\.setVisible\(record\.tabId === activeTabId\)/)
  assert.match(deviceViewManager, /canShowViews\(\): boolean/)
  assert.match(deviceViewManager, /return this\.workspaceVisible && !this\.browserOverlayOpen/)
  assert.match(deviceViewManager, /setVisibleForDevice\(tabId: string, deviceId: string, visible: boolean\)/)
  assert.match(deviceViewManager, /disposeDevice/)
  assert.match(deviceViewManager, /reloadDevice/)
  assert.match(deviceViewManager, /webContents\.reload\(\)/)
  assert.match(deviceViewManager, /captureDeviceScreenshot\(tabId: string, deviceId: string\): Promise<ScreenshotResult>/)
  assert.match(deviceViewManager, /captureScreenshot\(this\.window, record\.handle\.view\.webContents/)
  assert.match(deviceViewManager, /disposeTab/)
  assert.match(deviceViewManager, /snapshot\(\): DeviceViewSnapshot\[\]/)
  assert.match(deviceViewManager, /navigationState/)
  assert.match(deviceViewManager, /setNavigationSync\(enabled: boolean\)/)
  assert.match(deviceViewManager, /setDevToolsTarget\(tabId: string \| null, deviceId: string \| null\)/)
  assert.match(deviceViewManager, /hasDevToolsTarget\(\): boolean/)
  assert.match(deviceViewManager, /activeTargetDescriptor\(\): \{ tabId: string; deviceId: string; webContentsId: number \} \| null/)
  assert.match(deviceViewManager, /startNetworkCapture\(\): Promise<void>/)
  assert.match(deviceViewManager, /networkEntries\(\): NetworkEntry\[\]/)
  assert.match(deviceViewManager, /startConsoleCapture\(\): Promise<void>/)
  assert.match(deviceViewManager, /consoleEntries\(\): ConsoleEntry\[\]/)
  assert.match(deviceViewManager, /storageSnapshot\(\): Promise<StorageSnapshot>/)
  assert.match(deviceViewManager, /removeCookie\(identity: CookieIdentity\)/)
  assert.match(deviceViewManager, /preserveNetworkLog: \(\) => boolean = \(\) => false/)
  assert.match(deviceViewManager, /preserveConsoleLog: \(\) => boolean = \(\) => true/)
  assert.match(deviceViewManager, /new NetworkCollector\(contents, Promise\.resolve\(\), \(\) => this\.sendDeviceNetworkChanged\(\), ensureAttached, this\.preserveNetworkLog\)/)
  assert.match(deviceViewManager, /new ConsoleCollector\(contents, ensureAttached, \(\) => this\.sendDeviceConsoleChanged\(\), this\.preserveConsoleLog\)/)
  assert.match(deviceViewManager, /new PageStorage/)
  assert.match(deviceViewManager, /navigationSyncEnabled/)
  assert.match(deviceViewManager, /syncingKeys/)
  assert.match(deviceViewManager, /syncRouteFrom/)
  assert.match(deviceViewManager, /routeDestination/)
  assert.match(deviceViewManager, /record\.tabId !== source\.tabId/)
  assert.match(deviceViewManager, /destination\.pathname = sourceUrl\.pathname/)
  assert.match(deviceViewManager, /destination\.search = sourceUrl\.search/)
  assert.match(deviceViewManager, /destination\.hash = sourceUrl\.hash/)
  assert.match(deviceViewManager, /removeChildView/)
  assert.match(browserView, /did-fail-provisional-load/)
  assert.match(browserView, /did-finish-load/)
  assert.match(workspaceManager, /const preserveNetworkLog = \(\): boolean => this\.settings\.getBrowserSettings\(\)\.networkPreserveLog/)
  assert.match(workspaceManager, /const preserveConsoleLog = \(\): boolean => this\.settings\.getBrowserSettings\(\)\.consolePreserveLog/)
  assert.match(workspaceManager, /new DeviceViewManager\(this\.window, workspaceSession, preserveNetworkLog, preserveConsoleLog, \(url, active\) => \{ tabs\.create\(url, false, active\) \}, \(tabId, state\) => \{/)
  assert.match(workspaceManager, /deviceViews\.setBrowserOverlayOpen\(this\.hasBrowserOverlay\(\)\)/)
  assert.match(workspaceManager, /new TabManager\(this\.window, workspaceSession, this\.workspaces\.size === 0, restoredTabs, \(snapshot\) => \{[\s\S]*this\.persistTabs\(data\.id, snapshot\)[\s\S]*this\.recordTabsHistory\(data\.id, snapshot\)[\s\S]*\}, \(tab\) => \{/)
  assert.match(workspaceManager, /deviceViews\.disposeTab\(tab\.id\)/)
  assert.match(workspaceManager, /activeDeviceViews\(\): DeviceViewManager/)
  assert.match(workspaceManager, /type ActiveChromiumTarget/)
  assert.match(workspaceManager, /resolveActiveTarget\(\): ActiveChromiumTarget \| null/)
  assert.match(workspaceManager, /this\.viewportPreset === 'devices-canvas'/)
  assert.match(workspaceManager, /workspace\.deviceViews\.activeTargetDescriptor\(\)/)
  assert.match(workspaceManager, /workspace\.tabs\.activeTargetDescriptor\(\)/)
  assert.match(workspaceManager, /requireActiveTarget\(\): ActiveChromiumTarget/)
  assert.match(workspaceManager, /deviceViews\.disposeTab\(tab\.id\)/)
  assert.match(workspaceManager, /workspace\.deviceViews\.dispose\(\)/)
  assert.match(workspaceManager, /syncDeviceOverlayVisibility\(\): void/)
  assert.match(workspaceManager, /workspace\.deviceViews\.setBrowserOverlayOpen\(open\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.ensureView\(deviceViewDescriptorSchema\.parse\(raw\)\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.disposeDevice\(tabIdSchema\.parse\(rawTabId\), deviceViewIdSchema\.parse\(rawDeviceId\)\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.reloadDevice\(tabIdSchema\.parse\(rawTabId\), deviceViewIdSchema\.parse\(rawDeviceId\)\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.captureDeviceScreenshot\(tabIdSchema\.parse\(rawTabId\), deviceViewIdSchema\.parse\(rawDeviceId\)\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.setVisibleForTab\(tabIdSchema\.parse\(rawTabId\), rawVisible\)/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.setVisibleForDevice\(tabIdSchema\.parse\(rawTabId\), deviceViewIdSchema\.parse\(rawDeviceId\), rawVisible\)/)
  assert.match(browserIpc, /setDeviceDevToolsTarget/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.setDevToolsTarget\(target\.tabId, target\.deviceId\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.startNetworkCapture\(\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.networkEntries\(\) \?\? \[\]/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.startConsoleCapture\(\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.consoleEntries\(\) \?\? \[\]/)
  assert.match(browserIpc, /requireActiveTarget\(\)\.tools\.storageSnapshot\(\)/)
  assert.match(browserIpc, /getDevicesCanvasLayout/)
  assert.match(browserIpc, /saveDevicesCanvasLayout/)
  assert.match(browserIpc, /devicesCanvasLayoutSchema\.parse\(raw\)/)
  assert.match(browserIpc, /setDevicesNavigationSync/)
  assert.match(browserIpc, /activeDeviceViews\(\)\.setNavigationSync\(enabled\)/)
  assert.match(preload, /devices: \{/)
  assert.match(preload, /deviceViewSnapshotSchema\.parse\(await ipcRenderer\.invoke\(browserChannels\.ensureDeviceView/)
  assert.match(preload, /browserChannels\.removeDeviceView/)
  assert.match(preload, /browserChannels\.reloadDeviceView/)
  assert.match(preload, /browserChannels\.captureDeviceScreenshot/)
  assert.match(preload, /screenshotResultSchema\.parse\(await ipcRenderer\.invoke\(browserChannels\.captureDeviceScreenshot/)
  assert.match(preload, /browserChannels\.setDeviceViewsVisible/)
  assert.match(preload, /browserChannels\.setDeviceViewVisible/)
  assert.match(preload, /setDevToolsTarget: async \(tabId, deviceId\) =>/)
  assert.match(preload, /browserChannels\.setDeviceDevToolsTarget/)
  assert.match(preload, /getLayout: async \(tabId\) => devicesCanvasLayoutSchema\.nullable\(\)\.parse/)
  assert.match(preload, /saveLayout: async \(tabId, layout\) =>/)
  assert.match(preload, /setNavigationSync: async \(enabled\) =>/)
  assert.match(preload, /browserChannels\.setDevicesNavigationSync/)
  assert.match(workspaceManager, /getDevicesCanvasLayout\(tabId: string\)/)
  assert.match(workspaceManager, /saveDevicesCanvasLayout\(tabId: string, layout: DevicesCanvasLayout\)/)
  assert.match(workspaceRepository, /getDevicesCanvasLayout\(workspaceId: string, tabId: string\)/)
  assert.match(workspaceRepository, /saveDevicesCanvasLayout\(workspaceId: string, tabId: string, layout: DevicesCanvasLayout\)/)
  assert.match(workspaceRepository, /WHERE workspace_id = \? AND tab_id = \?/)
  assert.match(workspaceRepository, /ON CONFLICT\(workspace_id, tab_id\)/)
  assert.match(database, /tab_id TEXT NOT NULL/)
  assert.match(database, /PRIMARY KEY \(workspace_id, tab_id\)/)
  assert.match(database, /PRAGMA user_version = 8/)
  assert.match(database, /device_canvas_layouts_next/)
  assert.match(workspaceRepository, /JSON\.stringify\(data\)/)
  assert.match(tabManager, /onTabClosed/)
  assert.match(tabManager, /this\.onTabClosed\(closed\)/)
  assert.match(appRenderer, /webviewRef = useRef<BrowserWebviewElement \| null>\(null\)/)
  assert.match(appRenderer, /webview\.addEventListener\('dom-ready', domReady\)/)
  assert.match(appRenderer, /webview\.addEventListener\('did-navigate', syncUrl\)/)
  assert.match(appRenderer, /webview\.addEventListener\('did-navigate-in-page', syncUrl\)/)
  assert.match(appRenderer, /webview\.removeEventListener\('dom-ready', domReady\)/)
  assert.match(appRenderer, /onNavigate\(device\.id, url\)/)
  assert.doesNotMatch(devicesCanvasStore, /WebContentsView|BrowserView|Electron/)
  assert.doesNotMatch(deviceViewManager, /toDataURL/)
  assert.match(deviceViewManager, /contents\.debugger\.attach\('1\.3'\)/)
  assert.doesNotMatch(deviceViewManager, /Emulation\.setDeviceMetricsOverride/)
  const deviceFrameSource = appRenderer.match(/function DeviceFrame[\s\S]*?function CanvasViewport/)?.[0] ?? ''
  assert.match(deviceFrameSource, /<webview/)
  assert.doesNotMatch(deviceFrameSource, /<iframe/)
})

test('device screenshots use the selected device web contents', () => {
  assert.match(screenshotCapture, /dialog\.showSaveDialog/)
  assert.match(screenshotCapture, /selection\.canceled \|\| !selection\.filePath/)
  assert.match(screenshotCapture, /contents\.capturePage\(undefined, \{ stayHidden: true \}\)/)
  assert.match(screenshotCapture, /image\.toPNG\(\)/)
  assert.match(screenshotCapture, /filenamePrefix = 'stackly'/)
  assert.match(deviceViewManager, /captureDeviceScreenshot/)
  assert.match(deviceViewManager, /record\.handle\.view\.webContents/)
  assert.doesNotMatch(deviceViewManager, /this\.window\.webContents[^]*captureDeviceScreenshot/)
})

test('network inspector captures the active Chromium target through CDP', () => {
  assert.match(networkCollector, /class NetworkCollector/)
  assert.match(networkCollector, /Network\.requestWillBeSent/)
  assert.match(networkCollector, /Network\.responseReceived/)
  assert.match(networkCollector, /Network\.loadingFinished/)
  assert.match(networkCollector, /Network\.loadingFailed/)
  assert.match(networkCollector, /sendCommand\('Network\.enable'\)/)
  assert.match(networkCollector, /requestHeaders: headers\(event\.request\.headers\)/)
  assert.match(networkCollector, /responseHeaders = headers\(event\.response\.headers\)/)
  assert.match(networkCollector, /entry\.status = event\.response\.status/)
  assert.match(networkCollector, /entry\.duration = Math\.max\(0, \(event\.timestamp - start\) \* 1000\)/)
  assert.match(networkCollector, /private readonly onNavigationStarted/)
  assert.match(networkCollector, /!isMainFrame \|\| isInPlace \|\| this\.preserveLog\(\)/)
  assert.match(networkCollector, /this\.contents\.on\('did-start-navigation', this\.onNavigationStarted\)/)
  assert.match(networkCollector, /this\.contents\.removeListener\('did-start-navigation', this\.onNavigationStarted\)/)
  assert.match(networkCollector, /debuggerApi\.removeListener\('message', this\.onMessage\)/)
  assert.match(networkCollector, /debuggerApi\.removeListener\('detach', this\.onDetach\)/)
  assert.match(networkCollector, /if \(this\.disposed\) return/)
  assert.match(networkCollector, /clear\(\): void/)
  assert.match(tabManager, /preserveNetworkLog: \(\) => boolean = \(\) => false/)
  assert.match(tabManager, /new NetworkCollector\(contents, Promise\.resolve\(\), \(\) => this\.sendNetworkChanged\(\), ensureAttached, this\.preserveNetworkLog\)/)
  assert.match(tabManager, /activeTargetDescriptor\(\): \{ tabId: string; webContentsId: number \} \| null/)
  assert.match(deviceViewManager, /activeTargetDescriptor\(\): \{ tabId: string; deviceId: string; webContentsId: number \} \| null/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.startNetworkCapture\(\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.networkEntries\(\) \?\? \[\]/)
})

test('error center combines console and network failures for the active target', () => {
  assert.match(browserContracts, /clearNetworkEntries: 'browser:network:clear'/)
  assert.match(preload, /clear: async \(\) => \{ await ipcRenderer\.invoke\(browserChannels\.clearNetworkEntries\) \}/)
  assert.match(browserIpc, /browserChannels\.clearNetworkEntries/)
  assert.match(workspaceManager, /clearNetworkEntries: \(\) => void/)
  assert.match(tabManager, /clearNetworkEntries\(\): void \{ this\.activeDevToolsTarget\(\)\?\.network\.clear\(\) \}/)
  assert.match(deviceViewManager, /clearNetworkEntries\(\): void \{[\s\S]*network\.clear\(\)/)
  assert.match(devPanel, /'errors' \| 'network'/)
  assert.match(devPanel, /\{ id: 'errors', label: 'Errors' \}/)
  assert.match(devPanel, /activePanel === 'errors'/)
  assert.match(devPanel, /<ErrorCenter key=\{networkKey\} targetLabel=\{targetLabel\} onOpenPanel=\{onPanelChange\}/)
  assert.match(errorCenter, /window\.devBrowser\.console\.startCapture\(\)/)
  assert.match(errorCenter, /window\.devBrowser\.network\.startCapture\(\)/)
  assert.match(errorCenter, /consoleEntries\.map\(consoleProblem\)/)
  assert.match(errorCenter, /networkEntries\.map\(networkProblem\)/)
  assert.match(errorCenter, /intentionalNetworkFailures/)
  assert.match(errorCenter, /window\.devBrowser\.console\.clear\(\), window\.devBrowser\.network\.clear\(\)/)
  assert.match(errorCenter, /onOpenPanel\(problem\.context\)/)
})

test('api inspector clones captured requests and supports cancellable manual sends', () => {
  assert.match(browserContracts, /apiRequestIdSchema = z\.uuid\(\)/)
  assert.match(browserContracts, /apiSendRequestSchema = z\.strictObject\(\{ id: apiRequestIdSchema, request: apiRequestSchema \}\)/)
  assert.match(browserContracts, /cancelApiRequest: 'browser:api:cancel'/)
  assert.match(preload, /apiSendRequestSchema\.parse\(\{ id, request \}\)/)
  assert.match(preload, /browserChannels\.cancelApiRequest/)
  assert.match(browserIpc, /const apiRequests = new Map<string, AbortController>\(\)/)
  assert.match(browserIpc, /apiRequests\.set\(payload\.id, controller\)/)
  assert.match(browserIpc, /sendApiRequest\(payload\.request, controller\.signal\)/)
  assert.match(browserIpc, /apiRequests\.get\(apiRequestIdSchema\.parse\(raw\)\)\?\.abort\(\)/)
  assert.match(apiClient, /window\.devBrowser\.network\.startCapture\(\)/)
  assert.match(apiClient, /blockedHeaderNames/)
  assert.match(apiClient, /safeHeaderText/)
  assert.match(apiClient, /entryToRequest/)
  assert.match(apiClient, /window\.devBrowser\.api\.send\(requestId, request\)/)
  assert.match(apiClient, /window\.devBrowser\.api\.cancel\(requestId\)/)
  assert.match(apiClient, /Manual history/)
  assert.match(styles, /\.api-captured/)
  assert.match(styles, /\.api-history/)
})

test('storage explorer supports JSON viewing and editing for scoped storage records', () => {
  assert.match(browserContracts, /sessionStorage: z\.array\(localStorageEntrySchema\)\.default\(\[\]\)/)
  assert.match(browserContracts, /storageMutationSchema = z\.discriminatedUnion\('area'/)
  assert.match(browserContracts, /setStorageValue: 'browser:storage:set-value'/)
  assert.match(preload, /setValue: async \(mutation\) => \{ await ipcRenderer\.invoke\(browserChannels\.setStorageValue, storageMutationSchema\.parse\(mutation\)\) \}/)
  assert.match(browserIpc, /storageMutationSchema\.parse\(raw\)/)
  assert.match(browserIpc, /tools\.setStorageValue/)
  assert.match(pageStorage, /DOMStorage\.getDOMStorageItems/)
  assert.match(pageStorage, /isLocalStorage: false/)
  assert.match(pageStorage, /DOMStorage\.setDOMStorageItem/)
  assert.match(pageStorage, /contents\.session\.cookies\.set/)
  assert.match(tabManager, /setStorageValue\(mutation: StorageMutation\)/)
  assert.match(deviceViewManager, /setStorageValue\(mutation: StorageMutation\)/)
  assert.match(storageInspector, /type ViewMode = 'tree' \| 'pretty' \| 'raw'/)
  assert.match(storageInspector, /function JsonNode/)
  assert.match(storageInspector, /MAX_TREE_NODES/)
  assert.match(storageInspector, /JsonEditor value=\{draft\}/)
  assert.match(storageInspector, /Discard unsaved changes/)
  assert.match(storageInspector, /navigator\.clipboard\.writeText/)
  assert.match(styles, /\.storage-explorer-body/)
  assert.match(styles, /\.storage-json-key/)
  assert.match(styles, /\.storage-editor/)
})

test('elements inspector reads DOM and selects page elements through the active CDP target', () => {
  assert.match(browserContracts, /elementsSnapshotSchema/)
  assert.match(browserContracts, /getElementsSnapshot: 'browser:elements:get-snapshot'/)
  assert.match(browserContracts, /startElementPicker: 'browser:elements:start-picker'/)
  assert.match(preload, /elementsSnapshotSchema\.parse\(await ipcRenderer\.invoke\(browserChannels\.getElementsSnapshot\)\)/)
  assert.match(browserIpc, /tools\.elementsSnapshot\(\)/)
  assert.match(browserIpc, /tools\.startElementPicker\(\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.elementsSnapshot\(\) \?\? \{ root: null, selectedNodeId: null, box: null \}/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.startElementPicker\(\)/)
  assert.match(pageElements, /DOM\.getDocument/)
  assert.match(pageElements, /Overlay\.setInspectMode/)
  assert.match(pageElements, /Overlay\.inspectNodeRequested/)
  assert.match(pageElements, /if \(!this\.inspecting\) return/)
  assert.match(pageElements, /version !== this\.pickerVersion/)
  assert.match(pageElements, /await this\.stopPicker\(false\)/)
  assert.match(pageElements, /this\.inspecting = false/)
  assert.match(pageElements, /Overlay\.hideHighlight/)
  assert.doesNotMatch(pageElements, /Overlay\.highlightNode/)
  assert.match(tabManager, /elementsSnapshot\(\): Promise<ElementsSnapshot>/)
  assert.match(tabManager, /activeDevToolsTarget\(\)\?\.elements\.stopPicker\(false\)/)
  assert.match(deviceViewManager, /elementsSnapshot\(\): Promise<ElementsSnapshot>/)
  assert.match(deviceViewManager, /activeDevToolsRecord\(\)\?\.devTools\?\.elements\.stopPicker\(false\)/)
  assert.match(devPanel, /\{ id: 'elements', label: 'Elements' \}/)
  assert.match(devPanel, /<ElementsInspector key=\{networkKey\}/)
  assert.match(elementsInspector, /function containsNode/)
  assert.match(elementsInspector, /scrollIntoView\(\{ block: 'nearest' \}\)/)
  assert.match(elementsInspector, /function DomNode/)
  assert.match(elementsInspector, /Select element/)
  assert.match(elementsInspector, /Stop selecting/)
  assert.match(elementsInspector, /event\.key !== 'Escape'/)
  assert.match(elementsInspector, /setPicking\(false\)/)
  assert.match(elementsInspector, /Search DOM/)
  assert.match(elementsInspector, /window\.devBrowser\.elements\.startPicker\(\)/)
  assert.match(styles, /\.elements-inspector/)
  assert.match(styles, /\.elements-tree/)
})

test('console inspector captures the active Chromium target through Runtime CDP', () => {
  assert.match(consoleCollector, /class ConsoleCollector/)
  assert.match(consoleCollector, /Runtime\.consoleAPICalled/)
  assert.match(consoleCollector, /Runtime\.exceptionThrown/)
  assert.match(consoleCollector, /sendCommand\('Runtime\.enable'\)/)
  assert.match(consoleCollector, /sendCommand\('Runtime\.evaluate'/)
  assert.match(consoleCollector, /awaitPromise: true/)
  assert.match(consoleCollector, /includeCommandLineAPI: true/)
  assert.match(consoleCollector, /generatePreview: true/)
  assert.match(consoleCollector, /level: 'command'/)
  assert.match(consoleCollector, /level: 'result'/)
  assert.match(consoleCollector, /async completions\(prefix: string\)/)
  assert.match(browserContracts, /executeConsoleExpression: 'browser:console:execute'/)
  assert.match(browserContracts, /getConsoleCompletions: 'browser:console:completions'/)
  assert.match(preload, /execute: async \(expression\)/)
  assert.match(preload, /completions: async \(prefix\)/)
  assert.match(browserIpc, /tools\.executeConsoleExpression\(consoleExpressionSchema\.parse\(expression\)\)/)
  assert.match(browserIpc, /tools\.consoleCompletions/)
  assert.match(tabManager, /executeConsoleExpression\(expression: string\)/)
  assert.match(deviceViewManager, /executeConsoleExpression\(expression: string\)/)
  assert.match(consoleInspector, /JavaScript console input/)
  assert.match(consoleInspector, /event\.key === 'Enter' && !event\.shiftKey/)
  assert.match(consoleInspector, /event\.key === 'ArrowUp'/)
  assert.match(consoleInspector, /window\.devBrowser\.console\.execute\(expression\)/)
  assert.match(consoleInspector, /window\.devBrowser\.console\.completions\(prefix\)/)
  assert.match(consoleInspector, /navigator\.clipboard\.writeText\(entry\.text\)/)
  assert.match(styles, /\.console-input-wrap/)
  assert.match(styles, /\.console-entry--command/)
  assert.match(styles, /\.console-entry--result/)
  assert.match(consoleCollector, /event\.type === 'warning' \? 'warn' : event\.type/)
  assert.match(consoleCollector, /\['log', 'info', 'warn', 'error', 'debug'\]\.includes\(level\)/)
  assert.match(consoleCollector, /this\.add\(\{ level: level as ConsoleEntry\['level'\]/)
  assert.match(consoleCollector, /this\.add\(\{ level: 'error'/)
  assert.match(consoleCollector, /stackText\(detail\.stackTrace\)/)
  assert.match(consoleCollector, /private readonly onDetach/)
  assert.match(consoleCollector, /private readonly onNavigationStarted/)
  assert.match(consoleCollector, /!isMainFrame \|\| isInPlace \|\| this\.preserveLog\(\)/)
  assert.match(consoleCollector, /this\.contents\.debugger\.removeListener\('message', this\.onMessage\)/)
  assert.match(consoleCollector, /this\.contents\.debugger\.removeListener\('detach', this\.onDetach\)/)
  assert.match(consoleCollector, /this\.contents\.removeListener\('did-start-navigation', this\.onNavigationStarted\)/)
  assert.match(consoleCollector, /this\.contents\.debugger\.on\('detach', this\.onDetach\)/)
  assert.match(consoleCollector, /this\.contents\.on\('did-start-navigation', this\.onNavigationStarted\)/)
  assert.match(consoleCollector, /clear\(\): void \{ this\.entries = \[\]; this\.onChange\(\) \}/)
  assert.match(tabManager, /preserveConsoleLog: \(\) => boolean = \(\) => true/)
  assert.match(tabManager, /new ConsoleCollector\(contents, ensureAttached, \(\) => this\.sendConsoleChanged\(\), this\.preserveConsoleLog\)/)
  assert.match(deviceViewManager, /new ConsoleCollector\(contents, ensureAttached, \(\) => this\.sendDeviceConsoleChanged\(\), this\.preserveConsoleLog\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.startConsoleCapture\(\)/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.consoleEntries\(\) \?\? \[\]/)
  assert.match(browserIpc, /resolveActiveTarget\(\)\?\.tools\.clearConsoleEntries\(\)/)
})
